name: json_utilities
description: A collection of json utilities to enhance the experience of working with json based models.
version: 0.1.4
author: Benjamin Krammel <adelholtz@gmail.com>
homepage: https://github.com/adelholtz/json_utilities
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
